name: Automated Build

on:
  push:
    branches: [main, githubActions]
  pull_request:
    branches: [main, githubActions]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: gulp
